Add tolerance option
rbardini/jest-it-up pull request #16
Opened 2023-02-28 21:13 UTC by JCorpe26

Add the ability to provide a tolerance amount to allow a bit of wiggle room for the new coverage. So it isn't updated to the exact amount.

| New Coverage  | Tolernace | Outcome |
| - | - | - |
| 50 | 5 | 45 |
| 66 | 1 | 65 |

2023-03-19 00:13 UTC, rbardini requested changes
Thanks, @JCorpe26!

Sorry for the belated review; added one small change request before merging this in ✨

2023-03-19 00:13 UTC, rbardini commented on bin/jest-it-up
> +    'keeps the new threshold below the current coverage',
I'd prefer to describe the option _value_ instead:

```suggestion
    'threshold difference from actual coverage',
```

Please remember to update the README accordingly—I recommend running `jest-it-up --help` and copy-pasting the output there.

2023-03-20 08:56 UTC, JCorpe26 commented
@rbardini Fair shout, I have updated this :) 🤞 Should be all good now

2023-03-26 14:44 UTC, rbardini approved these changes

2023-03-26 14:46 UTC, merged